name: Expo React Native CI Debug

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: Source
        run: npm install

      - name: Run lint
        working-directory: Source
        run: npm run lint

      - name: Run tests
        working-directory: Source
        run: npm test

      - name: Build Expo project
        working-directory: Source
        run: npx expo build:ios


      - name: Build Expo project
        working-directory: Source
        run: npx expo build:web
